create database Projects;
select * from swiggy_data1;

--Data Validation and cleaning
--NULL Check

SELECT 
SUM(CASE WHEN STATE IS NULL THEN 1 ELSE 0 END) AS NULL_STATE,
SUM(CASE WHEN CITY IS NULL THEN 1 ELSE 0 END) AS NULL_CITY,
SUM(CASE WHEN ORDER_DATE IS NULL THEN 1 ELSE 0 END) AS NULL_ORDER_DATE,
SUM(CASE WHEN Restaurant_Name IS NULL THEN 1 ELSE 0 END) AS NULL_Restraurant_Name,
SUM(CASE WHEN Location IS NULL THEN 1 ELSE 0 END) AS NULL_Location,
SUM(CASE WHEN Category IS NULL THEN 1 ELSE 0 END) AS NULL_Category,
SUM(CASE WHEN Dish_Name IS NULL THEN 1 ELSE 0 END) AS NULL_Dish,
SUM(CASE WHEN Price_INR IS NULL THEN 1 ELSE 0 END) AS NULL_Rrice,
SUM(CASE WHEN Rating IS NULL THEN 1 ELSE 0 END) AS NULL_Rating,
SUM(CASE WHEN Rating_count IS NULL THEN 1 ELSE 0 END) AS NULL_Rating_count
FROM swiggy_data1

--Blank or Empty Strings
SELECT * FROM SWIGGY_DATA1 WHERE STATE='' OR CITY='' OR RESTAURANT_NAME='' OR LOCATION='' OR CATEGORY ='' OR DISH_NAME=''


--DUPLICATE DETECTION
SELECT STATE,CITY,ORDER_DATE,RESTAURANT_NAME,LOCATION,CATEGORY,DISH_NAME,PRICE_INR,RATING,RATING_COUNT,COUNT(*) AS CNT
FROM SWIGGY_DATA1 GROUP BY STATE,CITY,ORDER_DATE,RESTAURANT_NAME,LOCATION,CATEGORY,DISH_NAME,PRICE_INR,RATING,RATING_COUNT
HAVING COUNT(*)>1

--DELETE DUPLICATE ROWS.
WITH CTE AS (
SELECT *,ROW_NUMBER() OVER (PARTITION BY STATE,CITY,ORDER_DATE,RESTAURANT_NAME,LOCATION,CATEGORY,DISH_NAME,PRICE_INR,RATING,RATING_COUNT
ORDER BY (SELECT NULL)) AS RN FROM swiggy_data1)
DELETE FROM CTE WHERE RN>1;

/*WITH CTE AS(
SELECT *,dense_RANK() OVER (PARTITION BY CITY ORDER BY PRICE_INR
DESC) AS RN FROM swiggy_data1)
SELECT * FROM CTE WHERE RN<=1 */                                         --just for practise. 


--CREATING SCHEMA
--DIMENSION TABLES          YE JO BHI NICHE TABLE HAI DIMENSION TABLES HAI.
--DATE TABLE
CREATE TABLE DIM_DATE(
DATE_ID INT IDENTITY(1,1) PRIMARY KEY,
FULL_DATE DATE,
YEAR INT,
MONTH INT,
MONTH_NAME VARCHAR(25),
QUARTER INT,
DAY INT,
WEEK INT
)

SELECT * FROM DIM_DATE

--DIM_LOCATION
CREATE TABLE DIM_LOCATION (
LOCATION_ID INT IDENTITY(1,1) PRIMARY KEY,
STATE VARCHAR(100),
CITY VARCHAR(100),
LOCATION VARCHAR(200)
);

--DIM_RESTAURANT
CREATE TABLE DIM_RESTAURANT (
RESTAURANT_ID INT IDENTITY(1,1) PRIMARY KEY,
RESTAURANT_NAME VARCHAR(200)
);

--DIM_CATEGORY
CREATE TABLE DIM_CATEGORY (
CATEGORY_ID INT  IDENTITY(1,1) PRIMARY KEY,
CATEGORY VARCHAR(200)
);

--DIM_DISH
CREATE TABLE DIM_DISH (
DISH_ID INT  IDENTITY(1,1) PRIMARY KEY,
DISH_NAME VARCHAR(200)
)


--FACT TABLE
CREATE TABLE FACT_SWIGGY_ORDERS (
ORDER_ID INT IDENTITY(1,1) PRIMARY KEY,

DATE_ID INT,
PRICE_INR DECIMAL(10,2),
RATING DECIMAL(4,2),
RATING_COUNT INT,

LOCATION_ID INT,
RESTAURANT_ID INT,
CATEGORY_ID INT,
DISH_ID INT,

FOREIGN KEY (DATE_ID) REFERENCES DIM_DATE(DATE_ID),
FOREIGN KEY (LOCATION_ID) REFERENCES DIM_LOCATION(LOCATION_ID),
FOREIGN KEY (RESTAURANT_ID) REFERENCES DIM_RESTAURANT(RESTAURANT_ID),
FOREIGN KEY (CATEGORY_ID) REFERENCES DIM_CATEGORY(CATEGORY_ID),
FOREIGN KEY (DISH_ID) REFERENCES DIM_DISH(DISH_ID)
);

--INSERT DATA INTO TABLES
INSERT INTO DIM_DATE (FULL_DATE,YEAR,MONTH,MONTH_NAME,QUARTER,DAY,WEEK)
SELECT DISTINCT 
ORDER_DATE,
YEAR(ORDER_DATE),
MONTH(ORDER_DATE),
DATENAME(MONTH,ORDER_DATE),
DATEPART(QUARTER,ORDER_DATE),
DAY(ORDER_DATE),
DATEPART(WEEK,ORDER_DATE)
FROM swiggy_data1
WHERE ORDER_DATE IS NOT NULL;

SELECT * FROM DIM_DATE

--DIM LOCATION
INSERT INTO DIM_LOCATION(STATE,CITY,LOCATION)
SELECT  DISTINCT STATE,CITY,LOCATION FROM swiggy_data1

SELECT * FROM DIM_LOCATION

--DIM RESTAURANT
INSERT INTO DIM_RESTAURANT(RESTAURANT_NAME)
SELECT  DISTINCT RESTAURANT_NAME FROM swiggy_data1

SELECT * FROM DIM_RESTAURANT

--DIM_CATEGORY
INSERT INTO DIM_CATEGORY(CATEGORY)
SELECT  DISTINCT CATEGORY FROM swiggy_data1

SELECT * FROM DIM_CATEGORY

--DIM DISH
INSERT INTO DIM_DISH(DISH_NAME)
SELECT DISTINCT DISH_NAME FROM swiggy_data1

SELECT * FROM DIM_DISH
SELECT * FROM SWIGGY_DATA1
--INSERT FACT TABLE
INSERT INTO FACT_SWIGGY_ORDERS (DATE_ID,PRICE_INR,RATING,RATING_COUNT,LOCATION_ID,RESTAURANT_ID,CATEGORY_ID,DISH_ID)
SELECT DD.DATE_ID,S.PRICE_INR,S.RATING,S.RATING_COUNT,DL.LOCATION_ID,DR.RESTAURANT_ID,DC.CATEGORY_ID,DSH.DISH_ID
FROM SWIGGY_DATA1 S JOIN DIM_DATE DD ON DD.FULL_DATE=S.ORDER_DATE
JOIN DIM_LOCATION DL ON DL.STATE=S.STATE AND DL.CITY=S.CITY AND DL.LOCATION=S.LOCATION
JOIN DIM_RESTAURANT DR ON DR.RESTAURANT_NAME = S.RESTAURANT_NAME
JOIN DIM_CATEGORY DC ON  DC.CATEGORY=S.Category
JOIN DIM_DISH DSH ON DSH.DISH_NAME=S.Dish_Name

SELECT * FROM FACT_SWIGGY_ORDERS

SELECT * FROM FACT_SWIGGY_ORDERS F
JOIN DIM_DATE D ON F.DATE_ID = D.DATE_ID
JOIN DIM_LOCATION L ON F.LOCATION_ID = L.LOCATION_ID
JOIN DIM_RESTAURANT R ON F.RESTAURANT_ID = R.RESTAURANT_ID
JOIN DIM_CATEGORY C ON F.CATEGORY_ID = C.CATEGORY_ID
JOIN DIM_DISH DI ON F.DISH_ID = DI.DISH_ID


--KPI'S
--TOTAL ORDERS
SELECT COUNT(ORDER_ID) AS TOTAL_ORDERS FROM FACT_SWIGGY_ORDERS

--TOTAL REVENUE (INR MILLION)
SELECT FORMAT(SUM(CONVERT(FLOAT,PRICE_INR))/1000000,'N2') + ' INR MILLION' AS TOTAL_REVENUE FROM FACT_SWIGGY_ORDERS

----AVERAGE DISH PRICE
SELECT FORMAT(AVG(CONVERT(FLOAT,PRICE_INR)),'N2') + ' INR ' AS AVG_DISH_PRICE FROM FACT_SWIGGY_ORDERS

--AVERAGE RATING
SELECT FORMAT(AVG(CONVERT(FLOAT,RATING)),'N2') AS AVERAGE_RATING FROM FACT_SWIGGY_ORDERS

--DATE-BASED ANALYSIS
--MONTHLY ORDER TRENDS

SELECT D.YEAR,D.MONTH,D.MONTH_NAME,COUNT(*) AS MONTHLY_ORDER_TRENDS FROM FACT_SWIGGY_ORDERS F
JOIN DIM_DATE D ON D.DATE_ID=F.DATE_ID GROUP BY D.YEAR,D.MONTH,D.MONTH_NAME ORDER BY COUNT(*) DESC

--SUM OF SALES BASED ON MONTH
SELECT D.YEAR,D.MONTH,D.MONTH_NAME,SUM(PRICE_INR) AS MONTHLY_ORDER_TRENDS FROM FACT_SWIGGY_ORDERS F
JOIN DIM_DATE D ON D.DATE_ID=F.DATE_ID GROUP BY D.YEAR,D.MONTH,D.MONTH_NAME ORDER BY SUM(PRICE_INR) DESC

--QUATER TREND
SELECT D.YEAR,D.QUARTER,COUNT(*) AS QUARTER_ORDER_TRENDS FROM FACT_SWIGGY_ORDERS F
JOIN DIM_DATE D ON D.DATE_ID=F.DATE_ID GROUP BY D.YEAR,D.QUARTER ORDER BY COUNT(*) DESC

--YEARLY TREND
SELECT D.YEAR,COUNT(*) AS YEAR_ORDER_TRENDS FROM FACT_SWIGGY_ORDERS F
JOIN DIM_DATE D ON D.DATE_ID=F.DATE_ID GROUP BY D.YEAR ORDER BY COUNT(*) DESC

--ORDERS BY DAY OF WEEK (MON-SUN)
SELECT DATENAME(WEEKDAY,D.FULL_DATE) AS DAY_NAME,
COUNT(*) AS TOTAL_ORDERS FROM FACT_SWIGGY_ORDERS F 
JOIN DIM_DATE D ON F.DATE_ID=D.DATE_ID GROUP BY DATENAME(WEEKDAY,D.FULL_DATE) ORDER BY COUNT(*) DESC

--TOP 10 CITIES BY ORDER VOLUME.
SELECT TOP 10 L.CITY,COUNT(*) AS TOTAL_ORDERS FROM FACT_SWIGGY_ORDERS F
JOIN DIM_LOCATION L ON F.LOCATION_ID = L.LOCATION_ID GROUP BY L.CITY ORDER BY COUNT(*) DESC

--TOP 10 CITIES BY REVENUE
SELECT TOP 10 L.CITY,SUM(PRICE_INR) AS TOTAL_REVENUE FROM FACT_SWIGGY_ORDERS F
JOIN DIM_LOCATION L ON F.LOCATION_ID = L.LOCATION_ID GROUP BY L.CITY ORDER BY SUM(PRICE_INR) DESC

--REVENUE CONTRIBUTION BY STATES.
SELECT L.STATE,SUM(PRICE_INR) AS TOTAL_REVENUE_BY_STATE FROM FACT_SWIGGY_ORDERS F
JOIN DIM_LOCATION L ON F.LOCATION_ID = L.LOCATION_ID GROUP BY L.STATE ORDER BY SUM(PRICE_INR) DESC

--FOOD PERFORMANCE
--TOP 10 RESTAURANTS BY ORDERS
SELECT TOP 10 R.RESTAURANT_NAME,SUM(PRICE_INR) AS TOP_RESTAURANTS FROM FACT_SWIGGY_ORDERS F
JOIN DIM_RESTAURANT R ON R.RESTAURANT_ID=F.RESTAURANT_ID GROUP BY R.RESTAURANT_NAME ORDER BY SUM(PRICE_INR) DESC

--TOP 10 CATEGORIES
SELECT TOP 10 C.CATEGORY, COUNT(*) AS TOP_10_CATEGORIES FROM FACT_SWIGGY_ORDERS F
JOIN DIM_CATEGORY C ON C.CATEGORY_ID=F.CATEGORY_ID GROUP BY C.CATEGORY ORDER BY COUNT(*) DESC



--MOST ORDERED DISH 
SELECT TOP 1 DI.DISH_NAME,COUNT(*) AS MOST_ORDERED FROM FACT_SWIGGY_ORDERS F
JOIN DIM_DISH DI ON DI.DISH_ID=F.DISH_ID GROUP BY DI.DISH_NAME ORDER BY COUNT(*) DESC

--CUISINE PERFORMANCE --> ORDERS+AVG RATING
SELECT C.CATEGORY,COUNT(*) AS TOTAL_ORDERS,FORMAT(AVG(CONVERT(FLOAT,F.RATING)),'N2') AS AVG_RATING FROM FACT_SWIGGY_ORDERS F
JOIN DIM_CATEGORY C ON C.CATEGORY_ID=F.CATEGORY_ID GROUP BY C.CATEGORY ORDER BY COUNT(*) DESC

--CUSTOMER SPENDING INSIGHTS...
SELECT
CASE 
WHEN CONVERT(FLOAT,PRICE_INR)<100 THEN 'UNDER 100'
WHEN CONVERT(FLOAT,PRICE_INR) BETWEEN 100 AND 199 THEN '100 - 199'
WHEN CONVERT(FLOAT,PRICE_INR) BETWEEN 200 AND 299 THEN '200 - 299'
WHEN CONVERT(FLOAT,PRICE_INR) BETWEEN 300 AND 499 THEN '300 - 499'
ELSE '500+'
END AS PRICE_RANGE,
COUNT(*) AS TOTAL_ORDERS FROM FACT_SWIGGY_ORDERS
GROUP BY 
CASE 
WHEN CONVERT(FLOAT,PRICE_INR)<100 THEN 'UNDER 100'
WHEN CONVERT(FLOAT,PRICE_INR) BETWEEN 100 AND 199 THEN '100 - 199'
WHEN CONVERT(FLOAT,PRICE_INR) BETWEEN 200 AND 299 THEN '200 - 299'
WHEN CONVERT(FLOAT,PRICE_INR) BETWEEN 300 AND 499 THEN '300 - 499'
ELSE '500+'
END
ORDER BY TOTAL_ORDERS DESC

--RATING COUNT DISTRIBUTION(1 TO 5)
SELECT RATING,COUNT(*) AS RATING_COUNT FROM FACT_SWIGGY_ORDERS GROUP BY RATING ORDER BY COUNT(*) DESC


----END















SELECT * FROM FACT_SWIGGY_ORDERS
SELECT * FROM DIM_CATEGORY









SELECT * FROM DIM_DATE


































































































































































